### PR TITLE
added div function to index

### PR DESCRIPTION
**Pull request by joseph-p-pasaoa**

### CODE REVIEW

**Comment by joseph-p-pasaoa** [comment]
@DouglasMacKrell @KathyPuma @Bpmauge

**Review by Briahana-Mauge — DISMISSED** [review]
instead of exporting div separately. add div to the Math object after PI

**Comment by joseph-p-pasaoa** [comment]
@Bpmauge @DouglasMacKrell @KathyPuma 
please reapprove commit

**Review by Briahana-Mauge — APPROVED** [review]

**Review by DouglasMacKrell — APPROVED** [review]

**Comment by joseph-p-pasaoa** [comment]
@DouglasMacKrell @Bpmauge @KathyPuma 
pls reapprove

**Review by DouglasMacKrell — APPROVED** [review]

**Review by Briahana-Mauge — APPROVED** [review]

**Pull request merged**
